# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Insecure.Nmap
PackageVersion: '7.95'
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2024-04-22
Installers:
- Architecture: x86
  InstallerUrl: https://nmap.org/dist/nmap-7.95-setup.exe
  InstallerSha256: C59B51D15B5965F27DB4C5BBD21793AD6B492C8C751836BA8BD43829D791146E
ManifestType: installer
ManifestVersion: 1.6.0
